version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school
      TZ: "Asia/Tokyo"
    ports:
      - 5433:5432
